### ISSUE TITLE
Question: How to access Envoy common options in updaters and models

### ISSUE THREAD

**Issue by catsmanac** [pyenphase/pyenphase#104]
While looking into adding multiphase support based on phase information in Envoy's ivp/meters endpoint, I couldn't find an existing way to access common Envoy class properties in the updaters update method, only envoy_data is provided.  

One example could be the envoy firmware version that may drive different models to be called from the updater. Similar for the supported_features, these are stored in the Envoy class, but each EnvoyUpdater stores it's own private features and the update method doesn't receive the Envoy supported_features like the probe method does.

In the example I have at hand the (to be) meters updater will probe ivp/meters and ideally set a phase_count on the Envoy usable by various updaters, models and pyenphase clients. As probe returns supportedfeatures for now it will set like either DUALPHASE or THREEPHASE features that end up in the Envoy supportedfeatures. These are however not accessible in the production updaters update method, production only sees it's own features and no common Envoy features or properties. 

Adding the meters endpoint to production updater will create a future issue when adding ivp/meters/readings endpoint to collect grid import and export from the CT meters for use with energy dashboards as this will need the information from the meters collector as well.

This is were I got stuck in adding multi-phase support in the same way other updaters and models where done. Didn't want to overhaul anything more as just using existing style and therefor my question. I'm probably overlooking something here, please bear with me, relatively new to python.

Thanks for your insights.

**Comment by bdraco** [comment]
The probe does keep a running list of supported features and passes them to the next one https://github.com/pyenphase/pyenphase/blob/c8cd95843db9512dd7c8f0cc38c52eba8f15702c/src/pyenphase/envoy.py#L282

So as long as you have the updater that provides those features high enough in the list, other probes should see them
https://github.com/pyenphase/pyenphase/blob/c8cd95843db9512dd7c8f0cc38c52eba8f15702c/src/pyenphase/envoy.py#L54

**Comment by bdraco** [comment]
I think what you are wanting is all the supported features you could refactor this line 

https://github.com/pyenphase/pyenphase/blob/c8cd95843db9512dd7c8f0cc38c52eba8f15702c/src/pyenphase/envoy.py#L303

To pass in self._supported_features

so it becomes something like

`await updater.update(data, self._supported_features)`

**Comment by catsmanac** [comment]
Thanks @bdraco. I assume the refactor should be first in it's own PR as it will hit all updaters?

**Comment by bdraco** [comment]
Yes separate PRs for sure.Please keep each PR as small as possible so we can review and merge quickly On Oct 22, 2023, at 9:10 PM, Arie Catsman ***@***.***> wrote:﻿
Thanks @bdraco. I assume the refactor should be first in it's own PR as it will hit all updaters?

**Comment by catsmanac** [comment]
Thanks @bdraco. 

looks like I can avoid a refactor by adding a sync_features method to the EnvoyUpdater class that will make all features available to all updaters update method. And for updaters method probe ordering in the right order worked.

As for the new feature I have it currently in 3 commits, a code change, new test fixture and update test

![afbeelding](https://github.com/pyenphase/pyenphase/assets/120491684/55c1a050-abbf-4e7d-af6a-75b8a27424ad)


And the 4th will be what we are now discussing. Finally a 5th will be the implementation of the multiphase support in the production updater and models.

Should these all be separate PR? The first 3 are code change and accompanying test updates which maybe could be 1?

**Comment by bdraco** [comment]
It's a bit difficult to give you feedback on that since I can't see the code but please do include the tests in each PR for the changes the PR makes
