### ISSUE TITLE
QUESTION on split phase mode and multiphase production data

### ISSUE THREAD

**Issue by catsmanac** [pyenphase/pyenphase#107]
While working on adding multi-phase data for production and consumption I hit test failures on the fixtures 7.3.517_system_2, 7.31.130_no_consumption  and 4.10.35. All of these report CT Meter setup as split phaseMode with 2 phases.

```
"phaseMode": "split",
"phaseCount": 2,
```

The production data does not include data for the 2 phases, which is the reason for the test failure. Based on the phasecount of 2 one would expect data for the 2 phases like with phaseMode Three. I'm not familiar with split phase use as that is used in US and not here in EU. Before changing any fixture data I best ask the question.

So there's at least 4 options:

1. The fixture has a production file from another single phase fixture
2. The fixture has a meter file from another split phase fixture
3. The envoy in split phasemode does not report individual phase data event though it reports 2 phases.
4. For these FW's the ?details=1 is needed as [described ](https://github.com/Matthew1471/Enphase-API/blob/main/Documentation/IQ%20Gateway%20API/General/Production.adoc) by @matthew1471, though this doesn't seem to be the case with newer ones.

Anyone experience with Split mode and installed meters? Is no phase details to be expected in split mode? Are these fixtures for split phase with production phase data?

Thanks

**Comment by catsmanac** [comment]
used defensive programming just in case.

**Comment by Matthew1471** [comment]
Hello,

"Split Phase" isn't very common in the UK.. however I was talking to someone on Reddit who had Split Phase and apparently it can be quite controversial calling it 2 phase (from the transformer it's still only 1 phase that has then been split).. In the UK we have Live and a Neutral (L-N) but in Split Phase you can have (L-L) where there is no neutral and the current is divided between the 2 wires.. in this instance you need 2 CT clamps (on each wire) as per the tech brief : https://enphase.com/en-au/download/two-phase-installations-enphase-microinverters-tech-note so both sides can be monitored.

The Production if small enough could not be Split Phase, each utility operator has a threshold of what the balance per phase should be... or.. the installer could have done split phase but then cheaped out on putting the 2 CT clamps on the Consumption and another 2 CT clamps on the Production.

Keep in mind that `phaseMode` specifies what the device is capable of monitoring (potentially set via a Grid Profile too) and it's the phaseCount that indicates what is actually being monitored.

**Comment by catsmanac** [comment]
Thanks @Matthew1471, reason I was asking is that some /production endpoint data I've seen for split phase mode and  phasecount 2 did not contain the phases in production and consumption, while data was in the meters endpoints. Like you explained, it varies and that's why I called it defensive coding. If phasecount is 2, I just don't assume 2 phases will be present in /production, if they are great, else no data to report. Never a dull moment with enphase.

**Comment by Matthew1471** [comment]
Looking at the source for production.json it's just getting that data from `[/ivp/meters/reports](https://github.com/Matthew1471/Enphase-API/blob/main/Documentation/IQ%20Gateway%20API/IVP/Meters/Reports/All.adoc)` anyway
