### ISSUE TITLE
Home Assistant Integration Quality Scale

### ISSUE THREAD

**Issue by cgarwood** [pyenphase/pyenphase#141]
Putting this here so as to not lose it in HA's issue tracker...

Silver 🥈
This integration is able to cope when things go wrong. It will not print any exceptions nor will it fill the log with retry attempts.

- [x] Satisfying all No score level requirements.
- [x] Connection/configuration is handled via a component.
- [x] Set an appropriate SCAN_INTERVAL (if a polling integration)
- [x] Raise [PlatformNotReady](https://developers.home-assistant.io/docs/integration_setup_failures/#integrations-using-async_setup_platform) if unable to connect during platform setup (if appropriate)
  EDIT 20240312: [see discussion reply](https://github.com/pyenphase/pyenphase/issues/141#issuecomment-1991122042) 
- [x] Handles expiration of auth credentials. Refresh if possible or print correct error and fail setup. If based on a config entry, should trigger a new config entry flow to re-authorize. ([docs](https://developers.home-assistant.io/docs/config_entries_config_flow_handler#reauthentication))
- [x] Handles internet unavailable. Log a warning once when unavailable, log once when reconnected.
- [x] Handles device/service unavailable. Log a warning once when unavailable, log once when reconnected.
  EDIT 20240312: [see discussion reply](https://github.com/pyenphase/pyenphase/issues/141#issuecomment-1991348099)
- [ ] Operations like service calls and entity methods (e.g. Set HVAC Mode) have proper exception handling. Raise ServiceValidationError on invalid user input and raise HomeAssistantError for other failures such as a problem communicating with a device. [Read more](https://developers.home-assistant.io/docs/core/platform/raising_exceptions) about raising exceptions.
  EDIT 20240312: [see discussion reply](https://github.com/pyenphase/pyenphase/issues/141#issuecomment-1992300785)
- [x] Set available property to False if appropriate ([docs](https://developers.home-assistant.io/docs/core/entity#generic-properties))
  EDIT 20240328: Set to met, see discussion below
  EDIT 20240312: [see discussion reply](https://github.com/pyenphase/pyenphase/issues/141#issuecomment-1991348099)
- [x] Entities have unique ID (if available) ([docs](https://developers.home-assistant.io/docs/entity_registry_index#unique-id-requirements))

Gold 🥇
This is a solid integration that is able to survive poor conditions and can be configured via the user interface.

- [ ] Satisfying all Silver level requirements.
- [x] Configurable via config entries.
- [x] Don't allow configuring already configured device/service (example: no 2 entries for same hub)
- [x] Discoverable (if available)
- [x] Set unique ID in config flow (if available)
- [x] Raise ConfigEntryNotReady if unable to connect during entry setup (if appropriate)
   EDIT: 20240328: Set to met, removed discussion by mistake
   EDIT 20240313 [see discussion reply](https://github.com/pyenphase/pyenphase/issues/141#issuecomment-1993929519)
- [x] Entities have device info (if available) ([docs](https://developers.home-assistant.io/docs/device_registry_index#defining-devices))
- [x] Tests
  EDIT 20240313 [See discussion reply](https://github.com/pyenphase/pyenphase/issues/141#issuecomment-1994250304)
  EDIT 20240723 Set to pass based on 99% HA coverage and 100% pyenphase coverage
- [x] Full test coverage for the config flow
- [x] Above average test coverage for all integration modules
  EDIT 20240313 [See discussion reply](https://github.com/pyenphase/pyenphase/issues/141#issuecomment-1994260468)
  EDIT 20240723 Set to pass based on 99% HA coverage and 100% pyenphase coverage
- [x] Tests for fetching data from the integration and controlling it ([docs](https://developers.home-assistant.io/docs/development_testing))
  EDIT 20240313 [See discussion reply](https://github.com/pyenphase/pyenphase/issues/141#issuecomment-1994250304)
- [x] Has a code owner ([docs](https://developers.home-assistant.io/docs/creating_integration_manifest#code-owners))
- [x] Entities only subscribe to updates inside async_added_to_hass and unsubscribe inside async_will_remove_from_hass ([docs](https://developers.home-assistant.io/docs/core/entity#lifecycle-hooks))
  EDIT 20230313 [See discussion reply](https://github.com/pyenphase/pyenphase/issues/141#issuecomment-1994400932)
- [x] Entities have correct device classes where appropriate ([docs](https://developers.home-assistant.io/docs/core/entity#generic-properties))
- [x] Supports entities being disabled and leverages Entity.entity_registry_enabled_default to disable less popular entities ([docs](https://developers.home-assistant.io/docs/core/entity#advanced-properties))
- [x] If the device/service API can remove entities, the integration should make sure to clean up the entity and device registry.
  EDIT 20240313 [See discussion reply](https://github.com/pyenphase/pyenphase/issues/141#issuecomment-1994414507)
- [x] When communicating with a device or service, the integration implements the diagnostics platform which redacts sensitive information.

Platinum 🏆
Best of the best. The integration is completely async, meaning it's super fast. Integrations that reach platinum level will require approval by the code owner for each PR.

- [ ] Satisfying all Gold level requirements.
- [ ] Set appropriate PARALLEL_UPDATES constant ([docs](https://developers.home-assistant.io/docs/integration_fetching_data#request-parallelism))
  EDIT 20240313 [See discussion reply](https://github.com/pyenphase/pyenphase/issues/141#issuecomment-1994472852)
- [x] Support config entry unloading (called when config entry is removed)
  EDIT 20240313 [See discussion topic](https://github.com/pyenphase/pyenphase/issues/141#issuecomment-1994482416)
- [x] Integration + dependency are async ([docs](https://developers.home-assistant.io/docs/asyncio_working_with_async))
- [x] Uses aiohttp or httpx and allows passing in websession (if making HTTP requests)
- [x] [Handles expired credentials](https://developers.home-assistant.io/docs/integration_setup_failures/#handling-expired-credentials) (if appropriate)

**Comment by catsmanac** [comment]
- [ ] Raise [PlatformNotReady](https://developers.home-assistant.io/docs/integration_setup_failures/#integrations-using-async_setup_platform) if unable to connect during platform setup (if appropriate).

Platforms are created using `await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)` after first initializing the Envoy object in `__init__:async_setup_entry`. Connection failure is caught before setting up the platforms

Would think this marks this item as met!?

**Comment by catsmanac** [comment]
- [ ] Operations like service calls and entity methods (e.g. Set HVAC Mode) have proper exception handling. Raise ServiceValidationError on invalid user input and raise HomeAssistantError for other failures such as a problem communicating with a device. [Read more](https://developers.home-assistant.io/docs/core/platform/raising_exceptions) about raising exceptions.

Scanning through the code this seems to be the current list for these:
- Number
  - [ ] envoy.set_reserve_soc
    - [ ] Raises ValueError or EnvoyFeatureNotAvailable checking values
  - [ ] envoy.update_dry_contact
    - [ ] Raises ValueError or EnvoyFeatureNotAvailable checking values

For Number these are activated by `async_set_native_value` methods. These have no specific error handling

- Select
  - [ ] envoy.set_storage_mode
    - [ ] raises TypeError for mode parameter
  - [ ] envoy.update_dry_contact
    - [x] Raises ValueError or EnvoyFeatureNotAvailable checking values

For Select these are activated by `async_select_option` methods. These have no specific error handling

- Switch
  - [ ] envoy.go_on_grid
    - [ ] Raises ValueError or EnvoyFeatureNotAvailable checking values
   - [ ] envoy.go_off_grid
    - [ ] Raises ValueError or EnvoyFeatureNotAvailable checking values
  - [ ] envoy.close_dry_contact
    - [ ] Raises EnvoyFeatureNotAvailable checking values
  - [ ] envoy.open_dry_contact
    - [ ] Raises EnvoyFeatureNotAvailable checking values
  - [ ] envoy.enable_charge_from_grid
    - [ ] Raises ValueError or EnvoyFeatureNotAvailable checking values
  - [ ] envoy.disable_charge_from_grid
    - [ ] Raises ValueError or EnvoyFeatureNotAvailable checking values

For Switch these are activated by `async_turn_on` or `async_turn_off` method. These have no specific exception handling

These all use _request which:
- [ ] raises EnvoyAuthenticationRequired
- [ ] raises EnvoyAuthenticationRequired for HTTPStatus.UNAUTHORIZED, HTTPStatus.FORBIDDEN
- [ ] Does not raise on other errors, which typically results in JSON stackdump (orjson.JSONDecodeError: unexpected character: line 1 column 1 (char 0))

Looks like ServiceValidationError or HomeAssistantError is not implemented

**Comment by catsmanac** [comment]
- [ ] Tests
 
## Analysis

Only test_sensors, test_diagnostics currently. (Test_config_flow available as well but that fulfills other requirement).

## Resolution

Add tests for:
- binary-sensor
- number
- select
- switch

I have these ready in same format as test_sensor, but can use some assistance in adding tests for the switches that can be activated.

[Back to top](https://github.com/pyenphase/pyenphase/issues/141#issue-2177389450)

**Comment by catsmanac** [comment]
- [ ] Above average test coverage for all integration modules

## Analysis

For this one we first need the [tests](https://github.com/pyenphase/pyenphase/issues/141#issuecomment-1994250304) added

## Resolution

tbd

[Back to top](https://github.com/pyenphase/pyenphase/issues/141#issue-2177389450)

**Comment by catsmanac** [comment]
- [ ] Entities only subscribe to updates inside async_added_to_hass and unsubscribe inside async_will_remove_from_hass ([docs](https://developers.home-assistant.io/docs/core/entity#lifecycle-hooks))

## Analysis

? Are we using this, do we even need it ?

## Resolution

[Back to top](https://github.com/pyenphase/pyenphase/issues/141#issue-2177389450)

**Comment by catsmanac** [comment]
- [ ]  If the device/service API can remove entities, the integration should make sure to clean up the entity and device registry.

## Analysis

Don't think a have API doing this, do we? If not this is met as it doesn't apply

## Resolution

No action needed, met by absence of feature.

[Back to top](https://github.com/pyenphase/pyenphase/issues/141#issue-2177389450)

**Comment by catsmanac** [comment]
- [ ] Set appropriate PARALLEL_UPDATES constant ([docs](https://developers.home-assistant.io/docs/integration_fetching_data#request-parallelism))

## Analysis

Add `paralellel_updates` to platforms if appropriate

```py
PARALLEL_UPDATES = 0
```
If the value is 0, the integration is itself responsible for limiting the number of parallel requests if necessary.

Seems this is applicable for 

- number
- select
- switch

Neither have it currently. We define `_async_update_data` which results in a default of 0. Is there need to limit this? I.e. only process button pushes sequentially?

## Resolution

Add to 3 platform files. When using 0 still behaves as currently.

[Back to top](https://github.com/pyenphase/pyenphase/issues/141#issue-2177389450)

**Comment by catsmanac** [comment]
- [ ] Support config entry unloading (called when config entry is removed)

## Analysis

Think this one is met. There's  `__init__:async_unload_entry` and `__init__:async_remove_config_entry_device`

## Resolution

Not needed, think this one passes

[Back to top](https://github.com/pyenphase/pyenphase/issues/141#issue-2177389450)

**Comment by catsmanac** [comment]
Closing this one as HA redefined the quality scale. See replacement #192
