### ISSUE TITLE
Add power-limiting feature for use in Home Assistant

### ISSUE THREAD

**Issue by pvmil** [pyenphase/pyenphase#178]
**Is your feature request related to a problem? Please describe.**
I would like to limit power production of my Enphase system
(this is the library as used in home assistant, right?)

**Describe the solution you'd like**
Enable by extending this library to enable integration in home-assistant with a slider or service call to limit power production

**Additional context**
I checked how to do this, it should be possible to limit power production

Example API Request (Pseudocode):
`POST /api/v1/systems/<system_id>/curtailment
Host: api.enphaseenergy.com
Authorization: Bearer <your_access_token>
Content-Type: application/json

{
    "power_limit_watts": 5000
}`

**Comment by cgarwood** [comment]
This API endpoint uses the Enphase cloud API, not the local API on the Envoy device. I haven't seen a local API endpoint that allows for curtailment unfortunately.

**Comment by pvmil** [comment]
Thanks for the fast feedback. I was not aware of this difference (and also prefer local APIs of course). 

Too bad this is not available, would be really valuable. 

I will close this request
