### ISSUE TITLE
ENVOY-S Standard running D7.6.175 is not recognized to use api/v1/production

### ISSUE THREAD

**Issue by catsmanac** [pyenphase/pyenphase#27]
**Describe the bug**

Pyenphase (0.9.0 used in Home assistant core-2023.9.0.dev0) with ENVOY-S-EU Standard (800-00656-r06) running D7.6.175 generates an error:

```
  File "/workspaces/ha-core-dev/homeassistant/components/enphase_envoy/coordinator.py", line 88, in _async_update_data
    return (await envoy.update()).raw
            ^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/pyenphase/envoy.py", line 252, in update
    system_production = EnvoySystemProduction.from_production(production_data)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/pyenphase/models/system_production.py", line 34, in from_production
    inverters = all_production[1]
                ~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```
Envoy.probe function decides to use URL_PRODUCTION rather then URL_PRODUCTION_V1. When forcing it to use URL_PRODUCTION_V1 it works fine with this Envoy model.

When disabling or indent line 'self._production_endpoint = URL_PRODUCTION' all runs well and uses correct data.

Possible solutions:

- indent line more, only if consumption is there use production.json
- use: 'if production and consumption:' to use production.json.

```
   async def probe(self) -> None:
        """Probe for model and supported features."""
        try:
            production_json: dict[str, Any] = await self.request(URL_PRODUCTION)
        except (json.JSONDecodeError, httpx.HTTPError) as e:
            _LOGGER.debug("Production endpoint not found at %s: %s", URL_PRODUCTION, e)
        else:
            production: list[dict[str, str | float | int]] | None = production_json.get(
                "production"
            )
            if production:
                for type_ in production:
                    if type_["type"] == "eim" and type_["activeCount"]:
                        self._supported_features |= SupportedFeatures.METERING
                        break
            consumption: list[
                dict[str, str | float | int]
            ] | None = production_json.get("consumption")
            if consumption:
                for meter in consumption:
                    meter_type = meter["measurementType"]
                    if meter_type == "total-consumption" and meter["activeCount"]:
                        self._supported_features |= SupportedFeatures.TOTAL_CONSUMPTION
                    elif meter_type == "net-consumption" and meter["activeCount"]:
                        self._supported_features |= SupportedFeatures.NET_CONSUMPTION
            self._production_endpoint = URL_PRODUCTION

        if not self._production_endpoint:
            for endpoint in (URL_PRODUCTION_V1, URL_PRODUCTION_JSON):
                try:
```
**To Reproduce**
Running Home assistant devcontainer and add enphase envoy. After entering credentials Envoy is added but starts registering the error in the log file.

**Additional context**

Production.json for ENVOY-S Standard D7.6.175. Numbers in production segment are wrong. Should use numbersr from V1/production

Production.json
```
{
  "production": [
    {
      "type": "inverters",
      "activeCount": 24,
      "readingTime": 1691320699,
      "wNow": 2317,
      "whLifetime": 118599
    }
  ],
  "storage": [
    {
      "type": "acb",
      "activeCount": 0,
      "readingTime": 0,
      "wNow": 0,
      "whNow": 0,
      "state": "idle"
    }
  ]
}
```
api/v1/production.json, these numbers are correct
```
{
  "wattHoursToday": 8353,
  "wattHoursSevenDays": 193658,
  "wattHoursLifetime": 6083914,
  "wattsNow": 2154
}
```

**Comment by bdraco** [comment]
This is a case we didn't consider where we need to get data from two end points for production and consumption. 

We can't just switch the end point because it will break compatibility with envoy_readers and everyone's data would change in ha

We need to write tests for all the systems we have before we could add support for this type of bifurcated set up.

Might be a month or two before we can get to the point of supporting that.

**Comment by bdraco** [comment]
Actually this will probably break production systems as well

I think we should consider reverting the ha changes back to the old version for now and wait to roll out the new pyenphase lib until we can support this case

If I had free to to finish it this week I would consider otherwise but I don't

**Comment by catsmanac** [comment]
> This is a case we didn't consider where we need to get data from two end points for production and consumption.

The ENVOY-S Standard has no consumption data at all. It resembles a legacy one with the inverters added.

**Comment by bdraco** [comment]
> > This is a case we didn't consider where we need to get data from two end points for production and consumption.
> 
> 
> 
> The ENVOY-S Standard has no consumption data at all. It resembles a legacy one with the inverters added.

I think fixing your specific case it's pretty simple.  It's the bifurcated case I'm worried about

**Comment by catsmanac** [comment]
Agree, there's more issue's we know I haven't even looking into in the new one. 

What I would do ([did](https://github.com/catsmanac/Envoy_2_Core_custom_test)) is build a custom integration with it and invite the testers in HA Core issue [88983](https://github.com/home-assistant/core/issues/88983)  to test with it or share their data. I realize it's not common practice, but in this case many of the Envoy users are surviving like this since it broke with new firmware.

**Comment by bdraco** [comment]
I forgot I wrote all the tests for envoy reader. We can pull them in here as it will get things moving faster and hopefully avoid the need to revert 

https://github.com/jesserizzo/envoy_reader/tree/main/tests/fixtures

**Comment by bdraco** [comment]
Working on a test set for this now

Can you post your inverters endpoint as well?

**Comment by catsmanac** [comment]
I will. I have a bunch data laying around from all testing we did last weeks.let me dig it up for your cases. might not be formatted as you need it.

**Comment by bdraco** [comment]
Great.  I'll try to get the directories set up in the next hour or so. Than you can PR it instead as it might be a bit easier

**Comment by bdraco** [comment]
@catsmanac I wrote the tests and made the dirs for the fixtures. https://github.com/pyenphase/pyenphase/tree/main/tests/fixtures

It would be great if you could add your data.  Even better if you can add tests for it, but happy to do that if you just want to add the fixtures

**Comment by catsmanac** [comment]
I'll have a stab at it, not too much experience with these test, but willing to learn. Will let you know if I get stuck.

We will need to introduce envoy type in addition to firmware version in some way. Envoy-s standard, metered and metered without connected CT clamps all run same version but return different results.

And legacy  < 3.9 returns an html info with lifetime production in there, not an xml info, nor a production page. Yes I had a tester for it who had a legacy and a new Envoy just installed and needed the new stuff.

**Comment by bdraco** [comment]
> I'll have a stab at it, not too much experience with these test, but willing to learn. Will let you know if I get stuck.
> 
> 
> 
> We will need to introduce envoy type in addition to firmware version in some way. Envoy-s standard, metered and metered without connected CT clamps all run same version but return different results.

That should be covered by this check https://github.com/pyenphase/pyenphase/blob/6d01261dc3d711f8b3907b9113a3c2ad8de546be/src/pyenphase/envoy.py#L189
> 
> 
> 
> And legacy  < 3.9 returns an html info with lifetime production in there, not an xml info, nor a production page. Yes I had a tester for it who had a legacy and a new Envoy just installed and needed the new stuff.

Home assistant doesn't allow scraping html so we likely won't add support for that

**Comment by bdraco** [comment]
@catsmanac 
```
bdraco@MacBook-Pro-9 pyenphase % ENVOY_HOST="ip" ENVOY_USERNAME="you@email.com" ENVOY_PASSWORD="pass" python3 devtools/fixture_collector.py
Fixtures written to enphase-7.3.130
Zip file written to enphase-7.3.130.zip
```

@joostlek  just added a fixture collector that might make it a lot easier

**Comment by catsmanac** [comment]
> That should be covered by this check

For the test data I meant, you would need 3 different fixtures with the same version label.

Envoy-s metered without CT clamps only returns 0 values in v1/production. Needs to use data from first production segment, but that only has wnow and lifetime, not today and last seven days. Real neat feature of last firmware

**Comment by bdraco** [comment]
> For the test data I meant, you would need 3 different fixtures with the same version label.

The dir names are arbitrary so we can do

X.Y.Z_no_ct_clamps
X.Y.Z_ct_clamps


etc

**Comment by catsmanac** [comment]
> Home assistant doesn't allow scraping html so we likely won't add support for that

Well current version of envoy_reader on pypi does it using regex. If you don't include it's going to be a breaking change for the old ones.

**Comment by catsmanac** [comment]
That worked just fine, this is for ENVOY-S EU Standard on 7.6.175. ENVOY-S metered en metered withouth clamps have some different ones I'll add later.

[enphase-7.6.175.zip](https://github.com/pyenphase/pyenphase/files/12270434/enphase-7.6.175.zip)

**Comment by bdraco** [comment]
> 

I marked the PR to switch libs as a breaking change https://github.com/home-assistant/core/pull/97862

**Comment by bdraco** [comment]
> That worked just fine, this is for ENVOY-S EU Standard on 7.6.175. ENVOY-S metered en metered withouth clamps have some different ones I'll add later.
> 
> [enphase-7.6.175.zip](https://github.com/pyenphase/pyenphase/files/12270434/enphase-7.6.175.zip)

Thanks. They were added in https://github.com/pyenphase/pyenphase/pull/35

**Comment by catsmanac** [comment]
> > 
> 
> I marked the PR to switch libs as a breaking change [home-assistant/core#97862](https://github.com/home-assistant/core/pull/97862)

Looking at 3.9.36 fixture I see you have an info.xml file there. How did you obtain that one?
In my testing with <3.9 and >= 3.9  I got html back in both cases for info.xml. If you know how to get xml for 3.9 then that may work for <3.9 as well!?

### <3.9

info.xml reports error html page with serial no in there
```
2023-07-26 12:15:03.067 DEBUG (MainThread) [custom_components.enphase_envoy.envoy_reader] HTTP GET Attempt #1: http://192.168.86.29/info.xml: False: Header:None
2023-07-26 12:15:03.091 DEBUG (MainThread) [custom_components.enphase_envoy.envoy_reader] Checking Token value: 
2023-07-26 12:15:03.091 DEBUG (MainThread) [custom_components.enphase_envoy.envoy_reader] Found empty token: 
2023-07-26 12:15:07.650 DEBUG (MainThread) [custom_components.enphase_envoy.envoy_reader] Fetched from http://192.168.86.29/info.xml: <Response [200 OK]>:     <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN">
    <html lang="en">
    <!-- START HEAD CONTENT -->
    <head>
      <title>error</title>
      <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
      <!-- include style sheet -->
.
.
          <td class="hdr_line" valign="middle" colspan="4">Envoy Serial Number: 121023267212</td>
.
```
and production returns html with production numbers
```
2023-07-21 12:41:38.290 DEBUG (MainThread) [custom_components.enphase_envoy.envoy_reader] HTTP GET Attempt #1: http://192.168.100.12/production: Header:None
2023-07-21 12:41:38.494 DEBUG (MainThread) [custom_components.enphase_envoy.envoy_reader] Fetched from http://192.168.100.12/production: <Response [200 OK]>:     <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN">
    <html lang="en">
    <!-- START HEAD CONTENT -->
    <head>
      <title>production</title>
      <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
      <!-- include style sheet -->
.
.
      <tr><td colspan="3">System has been live since
                             <div class=good>Thu Oct 18, 2012 03:20 PM PDT</div></td></tr>
      <tr><td>Currently</td>    <td>    0 W</td></tr><tr><td>Today</td>     <td> 5.36 kWh</td></tr><tr><td>Past Week</td>    <td>  362 kWh</td></tr><tr><td>Since Installation</td>    <td>  172 MWh</td></tr>
.
```
and v1/production
```
2023-07-21 12:41:37.906 DEBUG (MainThread) [custom_components.enphase_envoy.envoy_reader] HTTP GET Attempt #1: http://192.168.100.12/api/v1/production: Header:None
2023-07-21 12:41:38.287 DEBUG (MainThread) [custom_components.enphase_envoy.envoy_reader] Fetched from http://192.168.100.12/api/v1/production: <Response [404 Not Found]>: {
  "status": 404,
  "error": "",
  "info": "Resource /api/v1/production not found",
  "moreInfo": ""
}
```

### \>=3.9

 info.xml
```
2023-07-25 07:35:50.393 DEBUG (MainThread) [custom_components.enphase_envoy.envoy_reader] HTTP GET Attempt #1: http://192.168.86.29/info.xml: Header:None
2023-07-25 07:35:50.480 DEBUG (MainThread) [custom_components.enphase_envoy.envoy_reader] Fetched from http://192.168.86.29/info.xml: <Response [200 OK]>:     <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN">
    <html lang="en">
    <!-- START HEAD CONTENT -->
    <head>
      <title>error</title>
      <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
      <!-- include style sheet -->
.
.
          <td class="hdr_line" valign="middle" colspan="4">Envoy Serial Number: 121445034107</td>
.
```
and v1/production
```
2023-07-25 07:35:50.499 DEBUG (MainThread) [custom_components.enphase_envoy.envoy_reader] HTTP GET Attempt #1: http://192.168.86.29/api/v1/production: Header:None
2023-07-25 07:35:50.507 DEBUG (MainThread) [custom_components.enphase_envoy.envoy_reader] Fetched from http://192.168.86.29/api/v1/production: <Response [200 OK]>: {
  "wattHoursToday": 290,
  "wattHoursSevenDays": 103157,
  "wattHoursLifetime": 35724674,
  "wattsNow": 522
}
```
and production.json
```
2023-07-26 12:15:10.143 DEBUG (MainThread) [custom_components.enphase_envoy.envoy_reader] Fetched from http://192.168.86.29/home.json: <Response [301 Moved Permanently]>:
```

**Comment by joostlek** [comment]
Oh you're right, I probably did something wrong when I tried to use git to check the differences of your files vs the files we already have

**Comment by joostlek** [comment]
The old fixture collector script converted the files into json, and since XML isn't json it fails. I made an update for it that also collects headers and status codes, so we can also create a valid test response when the endpoint isn't available. Checkout the file in https://github.com/pyenphase/pyenphase/pull/43

**Comment by catsmanac** [comment]
Here's an updated 7.6.175 For ENVOY-S EU Standard.

[enphase-7.6.175-standard.zip](https://github.com/pyenphase/pyenphase/files/12280653/enphase-7.6.175-standard.zip)

**Comment by bdraco** [comment]
> ### <3.9
> info.xml reports error html page with serial no in there

envoy_reader scrapes out the serial via a regex https://github.com/jesserizzo/envoy_reader/blob/0d3fb696519d487d14b0fff7def7d77ab2173cff/envoy_reader/envoy_reader.py#L402

With ADR004 we aren't allowed to do that for a core integration.  I realize that was the status quo for a long time, but it should not have been allowed.

**Comment by bdraco** [comment]
If we wanted to add support for < 3.9, we would need to either get an exception to ADR004 which is unlikely, or get ADR004 changed to allow scraping when older firmware requires it but newer firmware provides non-scraping methods.  That seems more likely to be accepted if its constrained in that manner.

If we want to go that route an https://github.com/home-assistant/architecture discussion needs to be started and it needs a champion

**Comment by bdraco** [comment]
Also the serial number fetch is coming from `/info` and `/info.xml` is not used so maybe that works on older firmware.

We need someone with the ancient firmware to run the new fixture collector to figure out the best way forward on that.

**Comment by catsmanac** [comment]
> We need someone with the ancient firmware to run the new fixture collector to figure out the best way forward on that.

The ones I know don't do any python stuff afaik. Best they can give you is browser access I expect or maybe a curl command.

**Comment by catsmanac** [comment]
> If we want to go that route an https://github.com/home-assistant/architecture discussion needs to be started and it needs a champion

Just gave it a try in [952](https://github.com/home-assistant/architecture/discussions/952)

**Comment by bdraco** [comment]
It looks like the answer for older version is to go the custom component route.

**Comment by bdraco** [comment]
> You may want to check where the cutoff point is and with which firmware the info.xml is available. Would a browser test to http://envoy.local/info.xml returning xml be sufficient proof?

I think so.

I have 4 envoys and all of them respond with the xml at http://envoy.local/info.xml and http://envoy.local/info
- [x] R3.9.36 (a1a93f) 192.168.106.159 (89 nem)
- [x] D3.17.3 (0e8c7a) 192.168.121.200 (81 nem)
- [x] D5.0.62 (5e57a9) 192.168.111.40 (12 nem)
- [x] D7.3.130 (91f206) 192.168.106.37 (89 nem plus)

**Comment by catsmanac** [comment]
Got feedback from testers, R3.11.30 gave 404 on /info.xml, /info gave xml and api/v1/production returns the well known data.
```
<envoy_info>
<time>1691436287</time>
<device>
<sn>121445034107</sn>
<pn>800-00069-r05</pn>
<software>R3.11.30</software>
```
R3.7.31 gave 404 on /info.xml, /info returns xml with version, /api/v1/production returns 404. /production works but it's html

![afbeelding](https://github.com/pyenphase/pyenphase/assets/120491684/63c38010-d849-4e84-8b0c-3bbac4615fa6)

He's been running this for **_11_** years. On the positive side he told he'll get an RMA for his legacy swapped for an ENVOY-s so Enphase can push new firmware to the envoy connected...

**Comment by catsmanac** [comment]
Just to let you know I synced ha core dev again and tested the new enphase_envoy. It contained pyenphase 0.14.1 and worked fine with my ENVOY-S standard 7.6.175  :smile:.

**Comment by bdraco** [comment]
So it seems like 3.7 won't work but 3.9 will

I guess we will find out if 3.8 works next month via reports

We can update the docs once we have better idea of what is going to be too old to work

**Comment by catsmanac** [comment]
> We can update the docs once we have better idea of what is going to be too old to work

Before I learned about this effort I worked on [updated docs](https://github.com/home-assistant/home-assistant.io/pull/28437#issuecomment-1665275709) as part of the discussion/activities in [88983](https://github.com/home-assistant/core/issues/88983) going on to promote a custom integration to new core version. But that's HA doc, no programmers  description as is probably needed here. Though HA could use an update as well.

**Comment by catsmanac** [comment]
I have the html example that comes back for that R3.7 production, the xml for info and the json 404 for api/v1/production laying around (somewhere) would that help?

HA itself has http and scrape integrations. Could they be used from HA Envoy side when needed?

**Comment by bdraco** [comment]
> I have the html example that comes back for that R3.7 production, the xml for info and the json 404 for api/v1/production laying around (somewhere) would that help?
> 
> 

Yes
> 
> HA itself has http and scrape integrations. Could they be used from HA Envoy side when needed?

Someone could probably make a scrape sensor using the scrape integration without too much work

**Comment by catsmanac** [comment]
This is what I have: [3.7.31-fixtures.zip](https://github.com/pyenphase/pyenphase/files/12293666/3.7.31-fixtures.zip)

**Comment by catsmanac** [comment]
As for scraping, as pyencharge is a public library, add the functionality to read the html using the regex. This does not require any additional packages.  Add a parameter to the envoy class signalling to not use webscraping (or other way around) or an additional method. Then in HA Core use that option to prevent webscraping. Someone (maybe me) then can clone the new HA Core enphase Envoy as custom integration with the scrape option enabled. Think that will meet ADR004.

**Comment by bdraco** [comment]
It would be better if we had a registration interface for another library to register a new endpoint for production and provide all the scraping logic. Than there is no scraping logic in this lib.

That could mean that a custom component would only need register a new endpoint for the production feature and provide the parser for it

**Comment by catsmanac** [comment]
Working on the 7.6.175_noct fixture I wonder if there's an issue with this one.

production reports eim activecount 0 (numbers there are wrong), but first segment has only wNow and whLifetime, no today nor 7day values.

Current logic in probe would recognize the activecount 0 and switch to api/v1/production but that is only reporting zero's.

In this case it should use wNow and whLifetime from first segment and set today and sevenday values to None. (Yes feature of this fw...)


```
{
	"production": [
		{
			"type": "inverters",
			"activeCount": 12,
			"readingTime": 1689167289,
			"wNow": 3429,
			"whLifetime": 634218
		},
		{
			"type": "eim",
			"activeCount": 0,
			"measurementType": "production",
			"readingTime": 1689167343,
			"wNow": -8.579,
			"whLifetime": 0.006,
			"varhLeadLifetime": 35.489,
			"varhLagLifetime": 46.254,
			"vahLifetime": 4781.293,
			"rmsCurrent": 0.192,
			"rmsVoltage": 709.67,
			"reactPwr": -0.0,
			"apprntPwr": 45.683,
			"pwrFactor": -0.28,
			"whToday": 0.006,
			"whLastSevenDays": 0.006,
			"vahToday": 4781.293,
			"varhLeadToday": 35.489,
			"varhLagToday": 46.254
		}
	],
```
and api/v1/production 
```
{
	"wattHoursToday": 0,
	"wattHoursSevenDays": 0,
	"wattHoursLifetime": 0,
	"wattsNow": 0
}
```

**Comment by catsmanac** [comment]
> the firmware inconsistency for these devices is pretty bad

not to mention how they document their api. Just sharing our findings while we where improving the custom integration and got to the point were we covered them all (except the next new fw probably).

And other item is multi-phase support, there will be up to 3 lines sections in production and consumption. One for each phase measured where phase is like 3 phase or 1 phase with ct behind different breakers.

```
			"lines": [
				{
					"wNow": 296.316,
					"whLifetime": 1028298.771,
					"varhLeadLifetime": 2628.982,
```
[production.txt](https://github.com/pyenphase/pyenphase/files/12295090/production.txt)

**Comment by bdraco** [comment]
https://github.com/pyenphase/pyenphase/pull/54/files#diff-b5dbe106863e55297cbef9b3b3108e0cfdbe4e64ddb5f00cc51f04ed4237c07eR24

I added a hook to register a new updater module.

The updater needs to implement probe and update

With probe, you return which features the updater will provide

With update, it should update the data for those features and set it on the EnvoyData dataclass

This should make it very easy to add new updaters and if you want register one that does scraping for the legacy devices

**Comment by bdraco** [comment]
I also added some tests for the registration interface an example on how one might make a scraper updater

https://github.com/pyenphase/pyenphase/blob/82efcec228dbe263c3f1c39e6ded3e9283fbfac2/tests/test_endpoints.py#L412

**Comment by catsmanac** [comment]
Thanks! It would need to clone the new HA Core and add it there and then offer as custom integration as many of these legacy users run newer ones as well and they probably want to continue the domain naming scheme for their long term history continuation.

**Comment by bdraco** [comment]
> Thanks! It would need to clone the new HA Core and add it there and then offer as custom integration as many of these legacy users run newer ones as well and they probably want to continue the domain naming scheme for their long term history continuation.

It could be as simple as a custom integration that requires core enphase_envoy as a dependency and that registers a newer updater as part of the code being loaded. It wouldn't have any other functionality other than patching in support for the old firmware to the library

**Comment by bdraco** [comment]
> > That one is a bit more difficult to fix
> 
> 
> 
> The method we used was both production and consumption segments being present and eim activecount is zero. The first item can set feature metered and the second can drive feature cts or something similar.
> 
> 
> 
> Info has <imeter> but I'm not sure how that's driven, could very well be true as this is ENVOY-S Metered.

Once we get fixtures in place for this version we can come up with a solution. Probably no rush as it wasn't supported before so no breaking change to not have it out of the gate

**Comment by catsmanac** [comment]
Original isse was resolved long time ago. Other suggestions noted. Thanks.
