### ISSUE TITLE
Firmware Variations

### ISSUE THREAD

**Issue by cgarwood** [pyenphase/pyenphase#3]
# Authentication
- `<host>/info` returns XML that contains the Envoy serial number and firmware version.
- For firmware < 7, Envoy uses HTTP authentication with user `installer` and a password that can be determined based on the Envoy serial number
- For firmware >= 7, Envoy uses token authentication that requires Enlighten cloud credentials to request

For firmware < 7, all we need is the hostname of the Envoy, the rest of the authentication can be determined automatically.
For firmware >= 7 we need the Envoy hostname and Enlighten credentials

Enphase has documentation on programmatically obtaining a token at https://enphase.com/download/iq-gateway-access-using-local-apis-or-local-ui-token-based-authentication-tech-brief

# Production Data
For firmware 5.x and 7,x production data is at `<host>/production.json`

There's also a `/api/v1/production` endpoint that returns some limited data on 3.x through 7.x:
```
{
  "wattHoursToday": 40162,
  "wattHoursSevenDays": 16307949,
  "wattHoursLifetime": 16348111,
  "wattsNow": 678
}
```

**Comment by bdraco** [comment]
Looks like we did all this 👍
