### ISSUE TITLE
wh Counters return 0

### ISSUE THREAD

**Issue by cgarwood** [pyenphase/pyenphase#74]
There seems to be a bug in firmware 7 & 8 where the whToday and whLastSevenDays counters for production or consumption (`/production.json`) will return 0.

Reported on the Enphase forums at:
https://support.enphase.com/s/question/0D53m00009INBskCAH/local-api-return-0-for-wh-counters-for-production-after-new-firmware-update

But the other API endpoints Enphase mention in that thread return a `401 Unauthorized` when using a system owner token.

Will need to continue monitoring.

**Comment by catsmanac** [comment]
In firmware 7 this occurs with Envoy metered and no CT's connected/configured. The Enphase forum one has activecount 0 for the meters. The numbers for api/v1/production in this case show all zero but there are reports of all kind of non-correct numbers. Only wNow and whLIfeTime in production[0] reportedly are ok. I think you have the test for activecount already in the code.

In firmware 8 all consumption values for whToday and whLastSevenDays for overall and all phases are 0 for metered with CT installed and configured. Only current and lifetime are reported for these. In this case activecount is 1. Haven't seen a FW8 metered without CT connected. Production seems ok. 

FW7 form the enphase forum
```
{
    "production": [{
            "type": "inverters",
            "activeCount": 9,
            "readingTime": 1688661240,
            "wNow": 779,
            "whLifetime": 922796
        }, {
            "type": "eim",
            "activeCount": 0,
            "measurementType": "production",
            "readingTime": 1688661242,
            "wNow": 0.493,
            "whLifetime": 0.0,
            "varhLeadLifetime": 0.0,
            "varhLagLifetime": 0.0,
            "vahLifetime": 0.0,
            "rmsCurrent": 0.365,
            "rmsVoltage": 248.809,
            "reactPwr": 0.2,
            "apprntPwr": 2.323,
            "pwrFactor": 0.0,
            "whToday": 0.0,
            "whLastSevenDays": 0.0,
            "vahToday": 0.0,
            "varhLeadToday": 0.0,
            "varhLagToday": 0.0
        }
   ```

**Comment by Matthew1471** [comment]
I suspect what's happening is the update has cleared `bin-roller` and so the aggregate data doesn't exist yet.. 

Before my system wasn't active a full day, week etc.. which is why I had to add some `if` statements to my Console example on my project : https://github.com/Matthew1471/Enphase-API/blob/main/Python/examples/gateway_console.py

I've flagged what I can see as `optional` in my [production.json docs](https://github.com/Matthew1471/Enphase-API/blob/main/Documentation/IQ%20Gateway%20API/General/Production.adoc)
